
name: 'dbt_bigquery_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_bigquery'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bigquery_project:
    example:
      +materialized: view

seeds:
  dbt_bigquery_project:
    +allow_quoted_newlines: true
